fibjs/fibjs

- fibjs/include/PKey.h
- fibjs/include/ifs/PKey.h
- fibjs/include/ifs/PKey.idl
- fibjs/src/crypto/PKey.cpp
Options for Multiple Hash Algorithm Support (NONE,MD2,MD4,MD5,SHA1,SHA224,SHA256,SHA384,SHA512,RIPEMD160)
> Options for Multiple Hash Algorithm Support

- test/unzip_test.js
> 修复windows下测试用例报错

- fibjs/include/ifs/zip.idl
> zip.idl 参数文档修正

- fibjs/include/ifs/ZipInfo.idl
> zipinfo idl

- fibjs/include/ZipFile.h
- fibjs/include/ifs/ZipFile.h
- fibjs/include/ifs/ZipFile.idl
- fibjs/src/zip/ZipFile.cpp
- test/unzip_test.js
> zip写入文件增加zip内文件名参数

- fibjs/src/zip/ZipFile.cpp
> 去除不必要的c_str()

- fibjs/fibjs.vcxproj
- fibjs/include/HttpClient.h
- fibjs/include/Isolate.h
- fibjs/include/ifs/HttpClient.h
- fibjs/include/ifs/HttpClient.idl
- fibjs/include/ifs/Socket.idl
- fibjs/include/ifs/http.h
- fibjs/include/ifs/http.idl
- fibjs/include/ifs/net.h
- fibjs/include/ifs/net.idl
- fibjs/src/http/HttpClient.cpp
- fibjs/src/http/HttpCookie.cpp
- fibjs/src/http/http.cpp
- fibjs/src/net/net.cpp
- test/http_test.js
- test/net_test.js
> Httpclient

- fibjs/src/process/SubProcess_win.cpp
修复windows下subprocess创建timer逻辑错误
> 修复windows下subprocess创建timer逻辑错误

- fibjs/include/ifs/HttpClient.idl
> 增加httpClient对象用法注释

- fibjs/include/ifs/gd.idl
- fibjs/include/utils.h
- fibjs/src/other/Image.cpp
> change doubleToInt to round

- fibjs/include/ifs/HttpClient.idl
修复 http://fibjs.org/db/d38/interfaceobject.html 页面渲染错误
> 修复http://fibjs.org/db/d38/interfaceobject.html页面渲染错误

- fibjs/include/ifs/process.h
- fibjs/include/ifs/process.idl
- fibjs/src/process/process.cpp
- test/process_test.js
> 增加process.version

- fibjs/include/ifs/process.h
- fibjs/include/ifs/process.idl
- fibjs/src/process/process.cpp
> feat:增加process.uptime

- fibjs/include/DBResult.h
- fibjs/include/List.h
- fibjs/include/Variant.h
- fibjs/include/ifs/List.h
- fibjs/include/ifs/List.idl
- fibjs/src/collection/List.cpp
- fibjs/src/db/sql/DBResult.cpp
- test/collection_test.js
Variant 的相等判断参照 http://www.ecma-international.org/ecma-262/6.0/#sec-strict-equality-comparison
List的 indexOf 参照 http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.indexof
> collection.List 增加 indexOf 方法

- fibjs/include/DBResult.h
- fibjs/include/List.h
- fibjs/include/ifs/List.h
- fibjs/include/ifs/List.idl
- fibjs/src/collection/List.cpp
- fibjs/src/db/sql/DBResult.cpp
- test/collection_test.js
参考了 ES2015 的SPEC，但是略有改动;
http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.lastindexof
> list 增加了lastIndexOf方法

- fibjs/include/Isolate.h
- fibjs/include/Trigger.h
- fibjs/include/WebSocket.h
- fibjs/include/ifs/EventEmitter.h
- fibjs/include/ifs/EventEmitter.idl
- fibjs/include/object.h
- fibjs/include/utils.h
- fibjs/src/base/Runtime.cpp
- fibjs/src/coroutine/Trigger.cpp
- test/event_files/worker.js
- test/trigger_test.js
> events, feat: add setMaxListeners & getMaxListeners & defaultMaxListers support

- fibjs/include/Stat.h
- fibjs/include/ifs/Stat.h
- fibjs/include/ifs/Stat.idl
- fibjs/include/ifs/fs.idl
- fibjs/src/fs/Stat.cpp
- test/fs_test.js
Stat: add uid and gid property, add fs test case
> Stat: add uid and gid property, add fs test case

- fibjs/include/HttpClient.h
- fibjs/src/http/HttpClient.cpp
- test/http_test.js
http: check http cookies validity
> http: check http cookies validity

- fibjs/include/ifs/Buffer.h
- fibjs/include/utils.h
- fibjs/src/global/Buffer.cpp
- idl/us-en/Buffer.idl
- idl/zh-cn/Buffer.idl
- test/buffer_test.js
- tools/util/gen_code.js
Buffer, feat: support Buffer.byteLength method.
> Buffer, feat: support Buffer.byteLength method.

- fibjs/include/ifs/Buffer.h
- fibjs/src/global/Buffer.cpp
- idl/us-en/Buffer.idl
- idl/zh-cn/Buffer.idl
- test/buffer_test.js
Buffer, feat: support Buffer.alloc method.
> Buffer, feat: support Buffer.alloc method.

- fibjs/include/encoding_iconv.h
- fibjs/include/ifs/Buffer.h
- fibjs/include/ifs/iconv.h
- fibjs/src/encoding/encoding_iconv.cpp
- fibjs/src/global/Buffer.cpp
- idl/us-en/Buffer.idl
- idl/us-en/iconv.idl
- idl/zh-cn/Buffer.idl
- idl/zh-cn/iconv.idl
- test/buffer_test.js
Buffer, feat: support Buffer.Compare and Buffer.isEncoding
> Buffer, feat: support Buffer.Compare and Buffer.isEncoding

- fibjs/include/HttpCookie.h
- test/http_test.js
HttpCookie, feat: path=/ as default value in cookie
> HttpCookie, feat: path=/ as default value in cookie

- fibjs/include/ifs/punycode.h
- fibjs/src/net/punycode.cpp
- idl/zh-cn/punycode.idl
- test/punycode_test.js
punycode, feat: support toUnicode and toASCII methods
> punycode, feat: support toUnicode and toASCII methods

- fibjs/include/Url.h
- fibjs/include/ifs/UrlObject.h
- fibjs/include/ifs/url.h
- fibjs/src/net/Url.cpp
- idl/us-en/Url.idl
- idl/us-en/punycode.idl
- idl/zh-cn/UrlObject.idl
- idl/zh-cn/url.idl
- test/url_test.js
url, refactor: standardize url.parse behavior
> url, refactor: standardize url.parse behavior

- fibjs/src/base/fibjs.cpp
- fibjs/src/zip/ZipFile.cpp
- test/selfzip_test.js
- test/unzip_test.js
unzip, bugfix: fix isZipFile error if filename is in unicode
> unzip, bugfix: fix isZipFile error if filename is in unicode

- fibjs/include/utils.h
- fibjs/src/base/utils.cpp
- fibjs/src/sandbox/SandBox_repl.cpp
> repl, feat: add 'Thown:' prefix in repl

- fibjs/src/global/Buffer.cpp
memmove can handle memory overlap
> change memcpy to memmove

- fibjs/include/ifs/console.h
- fibjs/src/console/console.cpp
- idl/us-en/console.idl
- idl/zh-cn/console.idl
添加 console.timeElapse()，输出当前计时值（不停止计时器）
> Add: console.timeElapse()

- idl/us-en/MySQL.idl
- idl/zh-cn/MySQL.idl
- test/fs_test.js
> Revert "[WIP] fix some literal mistake."

- idl/zh-cn/ws.idl
> fix typo in doc

- fibjs/scripts/opt_tools/install.js
> option, bugfix: fix JSON parse problem for node modules information

- tools/util/gen_ts_type.js
> tools, feat: mark all 'Object' as 'object'

- idl/us-en/MySQL.idl
- idl/zh-cn/MySQL.idl
- test/fs_test.js
> tools, feat: fix some literal mistake.

- fibjs/include/ifs/process.h
- fibjs/src/process/process.cpp
- idl/zh-cn/process.idl
- test/process_test.js
> process, feat: add property `pid` to get current process id.

- .travis.yml
- .travis/build.sh
- .travis/test.sh
> build, bugfix: clang build env

- fibjs/src/os/os_linux.cpp
If execute fibjs on the official ubuntu docker image(such as 18.04, 16.04, 14.04), `os.uptime()` will throw: 
```
/home/ci/test/os_test.js:18:24
uptime: os.uptime(),
^
Error: [2] No such file or directory
at Object.it (/home/ci/test/os_test.js:18:24)
at /home/ci/test/main.js:70:6
```
We can fix this error by remove the dlopen.
> fix: librt.so not found on ubuntu

- .travis/test.sh
> test, bugfix: fix the qemu test env

- .travis.yml
> test, feat: skip test when releasing.

- fibjs/src/os/os_posix.cpp
- test/os_test.js
> os, bugfix: os.homedir() fallback should work

- .travis/test.sh
> test, bugfix: enable the full arm test env

- fibjs/src/process/process.cpp
- test/process/exec.chargeable.js
- test/process_test.js
> process, bugfix: use real pipe-like struct to initial stdio in process.

- fibjs/src/os/os_win.cpp
>  os, bugfix: fix os.homedir() when USERPROFILE not set on Windows

- .travis/test.sh
> test, bugfix: fix the arm64 test env

- test/io_test.js
- test/main.js
- test/process/exec.chargeable.js
> test, feat: basic test cases about io

- fibjs/src/io/AsyncIO_iocp.cpp
> io, feat: improve payload size when processing async read in win32.

- test/path_test.js
> test, feat: add path.resolve root test case

- fibjs/src/process/SubProcess_posix.cpp
- fibjs/src/process/SubProcess_win.cpp
- idl/us-en/process.idl
- idl/zh-cn/process.idl
- test/_subprocess_check/.gitignore
- test/_subprocess_check/generator.process_env_keys.js
- test/_subprocess_check/index.js
- test/gui_test.js
- test/main.js
- test/opt_tools_test/index.js
- test/process/exec.dns.js
- test/process/exec.env_kvs.js
- test/process_test.js
> process, fix: make required envs' kv fallback to the ones of parent process.

- test/internal_test/helpers.js
- test/opt_tools_test/index.js
> test, fix: normalize internal & opt_tools' test cases.

- fibjs/include/HttpMessage.h
- fibjs/src/http/HttpClient.cpp
- fibjs/src/http/HttpMessage.cpp
- test/http_test.js
> http, bugfix: use empty body for HEAD request.

- .travis.yml
- .travis/release.sh
> ci, feat: use beta branch to release prerelase fibjs.

- fibjs/include/SubProcess.h
- fibjs/include/ifs/SubProcess.h
- fibjs/include/ifs/process.h
- fibjs/src/process/SubProcess_posix.cpp
- fibjs/src/process/SubProcess_win.cpp
- fibjs/src/process/process.cpp
- fibjs/src/process/process_win.h
- idl/us-en/SubProcess.idl
- idl/us-en/process.idl
- idl/zh-cn/SubProcess.idl
- idl/zh-cn/process.idl
- test/process/exec.ppid.js
- test/process_test.js
> process, feat: support `process.ppid` and `SubProcess::ppid`.

- fibjs/include/DBResult.h
- fibjs/include/Variant.h
> Variant, feat: support transform double to Variant.

- fibjs/src/global/Buffer.cpp
- test/buffer_test.js
> Buffer, feat: support static Buffer::compare

- fibjs/include/SubProcess.h
- fibjs/include/ifs/SubProcess.h
- fibjs/src/process/SubProcess.cpp
- fibjs/src/process/SubProcess_posix.cpp
- fibjs/src/process/SubProcess_win.cpp
- idl/zh-cn/SubProcess.idl
- test/process/exec.stderr.js
- test/process/exec.stdout.js
- test/process_test.js
> SubProcess, feat: support stderr.

- fibjs/src/encoding/encoding_json.cpp
> encoding, bugfix: use input's reference in json_parser to keep it alive.

- fibjs/src/base/v8_api.cpp
- fibjs/src/global/Buffer.cpp
> build, bugfix: remove hard dependency on vcruntime-about dll for windows.

- fibjs/include/v8_api.h
- fibjs/src/base/v8_api.cpp
- fibjs/src/encoding/encoding_json.cpp
> build, bugfix: fixup compilation error on windows.

- fibjs/include/HttpClient.h
- fibjs/include/ifs/HttpClient.h
- fibjs/src/http/HttpClient.cpp
- idl/zh-cn/HttpClient.idl
- test/http_test.js
> HttpClient, feat: support `sslVerification` getter/setter on HttpClient.

- fibjs/src/base/EventEmitter.cpp
> core, refactor: refactor jsTrigger, replace pointless subclass of AsyncEvent with call to `syncCall`.

- fibjs/src/base/options.cpp
> core, feat: SetDcheckErrorHandler for DEBUG mode.

- fibjs/include/AsyncCall.h
- fibjs/include/Chain.h
- fibjs/include/Fiber.h
- fibjs/include/Isolate.h
- fibjs/include/Runtime.h
- fibjs/include/Timer.h
- fibjs/include/fibjs.h
- fibjs/include/object.h
- fibjs/program/src/fibjs.cpp
- fibjs/src/base/EventEmitter.cpp
- fibjs/src/base/Runtime.cpp
- fibjs/src/base/acPool.cpp
- fibjs/src/base/date.cpp
- fibjs/src/base/fibjs_main.cpp
- fibjs/src/coroutine/Condition.cpp
- fibjs/src/coroutine/Event.cpp
- fibjs/src/coroutine/Fiber.cpp
- fibjs/src/coroutine/Lock.cpp
- fibjs/src/coroutine/Semaphore.cpp
- fibjs/src/coroutine/Worker.cpp
- fibjs/src/coroutine/coroutine.cpp
- fibjs/src/gui/windows/WebView.cpp
- fibjs/src/io/AsyncIO_ev.cpp
- fibjs/src/io/AsyncIO_iocp.cpp
- fibjs/src/os/Service_win.cpp
- fibjs/src/process/SubProcess_posix.cpp
- fibjs/src/process/SubProcess_win.cpp
> core, feat: make Fiber management more semantic.

- fibjs/src/io/AsyncIO_ev.cpp
> core, feat: make ev-based AsyncIO more reable.

- fibjs/include/ifs/path.h
- fibjs/include/ifs/path_posix.h
- fibjs/include/ifs/path_win32.h
- fibjs/include/path.h
- fibjs/include/utils.h
- fibjs/src/fs/path_posix.cpp
- fibjs/src/fs/path_win32.cpp
- idl/zh-cn/path.idl
- idl/zh-cn/path_posix.idl
- idl/zh-cn/path_win32.idl
- test/path_test.js
> path, feat: support path.format/path.parse

- .gitignore
- fibjs/build
- fibjs/include/FSWatcher.h
- fibjs/program/CMakeLists.txt
- fibjs/program/build
- fibjs/src/fs/AsyncFSIO.cpp
- fibjs/src/fs/fs.cpp
> fs, bugfix: fixup crash when trying to close FSWatcher.

- .travis/test.sh
- fibjs/include/AsyncUV.h
- fibjs/include/FSWatcher.h
- fibjs/include/StatsWatcher.h
- fibjs/include/ifs/StatsWatcher.h
- fibjs/include/ifs/fs.h
- fibjs/src/fs/AsyncFSIO.cpp
- fibjs/src/fs/fs.cpp
- idl/zh-cn/FSWatcher.idl
- idl/zh-cn/StatsWatcher.idl
- idl/zh-cn/fs.idl
- test/fswatch_test.js
- test/fswatch_test/hold2.js
- test/fswatch_test/hold3.js
> fs, feat: support `fs.watchFile`/`fs.unwatchFile`.

- fibjs/include/FSWatcher.h
- fibjs/src/fs/AsyncFSIO.cpp
> fs, feat: hold `FSWatcher->start()` before uv binding finished.

- fibjs/src/gui/darwin/WebView.h
- fibjs/src/gui/darwin/WebView.mm
- fibjs/src/gui/darwin/ns-api.h
- fibjs/src/gui/darwin/ns-api.impl.inl.mm
> gui, feat: simplify implementation of WebView in darwin.

- fibjs/src/gui/windows/WebView.cpp
- fibjs/src/gui/windows/script/console.js
- fibjs/src/gui/windows/script/console_js.cpp
- test/gui_test.js
> gui, feat: rename protocol 'fs:' to 'fs://' for WebView on win32.

- fibjs/src/gui/darwin/WebView.h
- fibjs/src/gui/darwin/WebView.mm
> gui, feat: use blocking-awake mode for NSAppMainRunLoopThread

- fibjs/src/encoding/encoding_msgpack.cpp
msgpack, feat: fix bug int/uint decode to null (解码int类型为null的问题
> msgpack, feat: fix bug int/uint decode to null

- fibjs/include/SubProcess.h
- fibjs/include/ifs/SubProcess.h
- fibjs/src/process/SubProcess_posix.cpp
- fibjs/src/process/SubProcess_win.cpp
- idl/us-en/SubProcess.idl
- idl/zh-cn/SubProcess.idl
- test/process_test.js
> SubProcess, feat: remove pointless SubProcess::ppid.

- fibjs/src/http/HttpFileHandler.cpp
- fibjs/src/io/RangeStream.cpp
- test/http_files/range_test/fake.js
- test/http_test.js
- test/io_test.js
> HttpFileHandler, feat: support http partial content request.

- fibjs/include/BufferedStream.h
- fibjs/include/MemoryStream.h
- fibjs/include/RangeStream.h
- fibjs/include/Socket.h
- fibjs/include/SslSocket.h
- fibjs/include/SubProcess.h
- fibjs/include/UVStream.h
- fibjs/include/ZlibStream.h
- fibjs/include/ifs/Stream.h
- fibjs/src/io/BufferedStream.cpp
- fibjs/src/io/MemoryCloneStream.cpp
- fibjs/src/io/MemoryStream.cpp
- fibjs/src/io/RangeStream.cpp
- fibjs/src/net/Socket.cpp
- fibjs/src/os/os_win.cpp
- fibjs/src/process/process.cpp
- fibjs/src/ssl/SslSocket.cpp
- idl/zh-cn/Stream.idl
- test/io_test.js
- test/process_test.js
> process, feat: test 'fd' property in process.std[in|out|err]

- fibjs/src/io/RangeStream.cpp
> RangeStream, bugfix: correct local `asyncStat` request for `RangeStream::stat`

- fibjs/include/ChildProcess.h
- fibjs/include/UVStream.h
- fibjs/src/os/os_win.cpp
- fibjs/src/process/ChildProcess.cpp
- fibjs/src/process/process.cpp
- fibjs/src/util/util_info.cpp
- test/child_process_test.js
- test/opt_tools_test/install_from_pkgjson/index.js
- test/opt_tools_test/install_raw/index.js
- test/process/const.env_keys.js
- test/process/exec.env_kvs.js
- test/process/exec.print_child_env.js
- test/process/exec.print_kvs.js
> [squash] fixup compilation error on windows.

- fibjs/include/Stat.h
- fibjs/include/ifs/Stat.h
- fibjs/src/fs/File.cpp
- fibjs/src/fs/Stat.cpp
- idl/zh-cn/Stat.idl
- test/fs_test.js
> [rebase]Stat, feat: use uv_fs* APIs to query stat from file system, more compatible APIs with nodejs.

- test/http_test.js
> http, feat: add test cases for httpClient whose 'sslVerification' set.

- fibjs/include/StatsWatcher.h
- fibjs/src/fs/AsyncFSIO.cpp
- fibjs/src/fs/fs.cpp
- test/fswatch_test.js
> StatsWatcher, bugfix: fixup unexpected thread holding occured on calling `fs.watchFile`.

- fibjs/include/UVStream.h
- test/process/exec.blocking_stdin.js
- test/process/exec.blocking_stdout.js
- test/process_test.js
> UVStream, bugfix: make fd of stdio work in blocking mode.

- fibjs/src/base/utils.cpp
> utils, bugfix: correct local variable `s_errors` in `getResultMessage`.

- fibjs/src/encoding/encoding_msgpack.cpp
- test/encoding_test.js
> msgpack, feat: support bigint pack. 

- fibjs/src/http/HttpClient.cpp
- idl/zh-cn/HttpClient.idl
- idl/zh-cn/http.idl
- test/http_test.js
> http, feat: support pack option for msgpack.

- fibjs/include/Isolate.h
- fibjs/include/ssl.h
- fibjs/src/base/Runtime.cpp
- fibjs/src/ssl/SslSocket.cpp
- fibjs/src/ssl/ssl.cpp
- test/ssl_test.js
> ssl, bugfix: crash on verify ssl.ca, #679

- fibjs/src/fs/fs_posix.cpp
- test/child_process_test.js
- test/fs_test.js
> fs, bugfix: fstat mode error when create directory and file.

- fibjs/src/gui/windows/WebView.cpp
- test/gui_files/html-script/absolute/.gitignore
- test/gui_files/html-script/absolute/absolute.js
- test/gui_files/html-script/relative/relative.html
- test/gui_files/html-script/relative/relative.js
- test/gui_files/html/tag-script/http.html
- test/gui_files/html/tag-script/http.js
- test/gui_test.js
> gui, bugfix: fixup resource request on win32 webview.

- fibjs/include/ifs/crypto.h
- fibjs/src/crypto/crypto.cpp
- idl/zh-cn/crypto.idl
- npm/types/dts/module/crypto.d.ts
- test/crypto_test.js
> crypto, feat: add crypto.getHashes()

- fibjs/src/encoding/encoding_msgpack.cpp
- test/encoding_test.js
msgpack, feat: support number_safe_int.
> msgpack, feat: support number_safe_int.

- fibjs/src/base/v8_api.cpp
> vender, feat: upgrade to use v8 7.8.285

- fibjs/src/global/Buffer.cpp
> Buffer, feat: optimize concat()

- fibjs/src/util/util_format_table.cpp
> console, bugfix: use hex as char literal for `console.table`, to avoid compilation error on msvc.

- fibjs/include/encoding.h
- fibjs/src/global/Buffer.cpp
- test/buffer_test.js
> Buffer, feat: support base64url

- build
> build, bugfix: illegal option of date on MacOS.

- fibjs/src/http/HttpClient.cpp
> http, bugfix: socks5 connect request / response

- fibjs/src/db/odbc/Odbc.cpp
- test/db_test.js
> bugfix, db: correct odbc parsing error of data column type on postgresql 14.

- fibjs/src/net/Url.cpp
- test/url_test.js
> bugfix, url: allow pass number type `port` to `url.format`.

- fibjs/include/HttpClient.h
- fibjs/include/ifs/HttpClient.h
- fibjs/include/ifs/http.h
- fibjs/src/http/HttpClient.cpp
- fibjs/src/http/HttpMessage.cpp
- fibjs/src/http/http.cpp
- idl/zh-cn/HttpClient.idl
- idl/zh-cn/http.idl
- npm/types/dts/interface/HttpClient.d.ts
- npm/types/dts/module/http.d.ts
- test/http_test.js
> http, feat: support http.head

- fibjs/include/SandBox.h
- fibjs/include/fibjs.h
- fibjs/include/ifs/SandBox.h
- fibjs/program/src/fibjs.cpp
- fibjs/src/base/Isolate.cpp
- fibjs/src/base/modules.cpp
- fibjs/src/sandbox/SandBox.cpp
- idl/zh-cn/SandBox.idl
- npm/types/dts/interface/SandBox.d.ts
- test/vm_test.js
> Sandbox, feat: support builtin module's alias with prefix `fibjs:`

- idl/zh-cn/WebSocket.idl
- npm/types/dts/interface/WebSocket.d.ts
> docs, bugfix: update websocket doc

- .gitignore
- tools/gen_index.js
1. update docs
2. ensure the correct path is used when using db
> docs, bugfix: update docs

- idl/zh-cn/url.idl
> docs, bugfix: URL typo

- fibjs/src/console/console.cpp
- fibjs/src/test/assert.cpp
- fibjs/src/util/util.h
- fibjs/src/util/util_format.cpp
- fibjs/src/util/util_format_table.cpp
- idl/zh-cn/console.idl
- idl/zh-cn/util.idl
- test/util_test.js
support max_array_length in inspect.
> util, feat: support max_array_length in inspect.

- fibjs/src/test/assert.cpp
- fibjs/src/util/util.h
- fibjs/src/util/util_format.cpp
- fibjs/src/util/util_format_table.cpp
- idl/zh-cn/console.idl
- idl/zh-cn/util.idl
- test/util_test.js
util, feat: support maxStringLength in inspect.
> util, feat: support maxStringLength in inspect.
